import { useState, useRef, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { HexColorPicker } from 'react-colorful';
import { cn } from '../lib/utils';
import { Input } from './ui/input';
import { Select, SelectTrigger, SelectContent, SelectItem } from './ui/select';
import type { SystemDef } from '../types.ts';

interface MepSystemDialogProps {
  open: boolean;
  onClose: () => void;
  onConfirm: (system: SystemDef) => void;
  /** Initial values. When omitted the dialog is in "add" mode. */
  initial?: SystemDef;
}

const DISCIPLINE_OPTIONS = [
  { value: 'hvac', label: 'HVAC' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'electrical', label: 'Electrical' },
  { value: 'fire', label: 'Fire Protection' },
  { value: 'data', label: 'Data / Telecom' },
];

const DEFAULT_COLOR = '#3b82f6';

/** Add / edit one row of `global/mep_system.csv`. Compact form: name +
 *  system_type code + color picker + discipline. The id is generated by the
 *  caller (sequential `sys-N`) and passed through `initial` on edit. */
export default function MepSystemDialog({ open, onClose, onConfirm, initial }: MepSystemDialogProps) {
  const { t } = useTranslation();
  const [name, setName] = useState(initial?.name ?? '');
  const [systemType, setSystemType] = useState(initial?.system_type ?? '');
  const [color, setColor] = useState(initial?.color || DEFAULT_COLOR);
  const [discipline, setDiscipline] = useState(initial?.discipline || 'hvac');
  const nameRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      setName(initial?.name ?? '');
      setSystemType(initial?.system_type ?? '');
      setColor(initial?.color || DEFAULT_COLOR);
      setDiscipline(initial?.discipline || 'hvac');
      setTimeout(() => nameRef.current?.select(), 0);
    }
  }, [open, initial]);

  if (!open) return null;

  const isEdit = !!initial;
  const dialogTitle = isEdit
    ? t('dialog.editMepSystem', 'Edit MEP System')
    : t('dialog.addMepSystem', 'Add MEP System');
  const dialogConfirm = isEdit
    ? t('dialog.save', 'Save')
    : t('dialog.add', 'Add');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const trimmedType = systemType.trim().toUpperCase();
    if (!trimmedType) return;
    onConfirm({
      id: initial?.id ?? '',  // caller assigns when adding
      system_type: trimmedType,
      name: name.trim(),
      color,
      discipline,
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={onClose}>
      <form
        className="w-80 rounded-lg border border-border bg-card p-4 shadow-xl"
        onClick={e => e.stopPropagation()}
        onSubmit={handleSubmit}
      >
        <div className="mb-3 text-[12px] font-semibold text-foreground">{dialogTitle}</div>

        <label className="mb-1 block text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {t('dialog.mepSystem.code', 'System Code')}
        </label>
        <Input
          ref={nameRef}
          className="mb-3 h-7 text-[12px] uppercase"
          value={systemType}
          onChange={e => setSystemType(e.target.value)}
          placeholder="CHWS"
          autoFocus
        />

        <label className="mb-1 block text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {t('dialog.name', 'Name')}
        </label>
        <Input
          className="mb-3 h-7 text-[12px]"
          value={name}
          onChange={e => setName(e.target.value)}
          placeholder="Chilled Water Supply"
        />

        <label className="mb-1 block text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {t('dialog.mepSystem.discipline', 'Discipline')}
        </label>
        <Select value={discipline} onValueChange={(v) => { if (v) setDiscipline(v); }}>
          <SelectTrigger className="mb-3 h-7 w-full rounded border border-input bg-transparent px-2 text-[12px]">
            <span className="truncate">
              {DISCIPLINE_OPTIONS.find(o => o.value === discipline)?.label ?? discipline}
            </span>
          </SelectTrigger>
          <SelectContent>
            {DISCIPLINE_OPTIONS.map(opt => (
              <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>

        <label className="mb-1 block text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {t('dialog.mepSystem.color', 'Color')}
        </label>
        <div className="mb-4 flex flex-col gap-2">
          {/* react-colorful: dependency-free, ~3kb, gives a real saturation
              square + hue strip rather than a native popout that varies by OS. */}
          <HexColorPicker
            color={color}
            onChange={setColor}
            className="!w-full"
          />
          <div className="flex items-center gap-2">
            <span
              className="size-7 shrink-0 rounded border border-border"
              style={{ backgroundColor: color }}
            />
            <Input
              className="h-7 flex-1 font-mono text-[12px]"
              value={color}
              onChange={(e) => {
                const v = e.target.value;
                // Accept whatever the user types; only push to the swatch when
                // it's a valid 3- or 6-digit hex so the picker doesn't jump
                // around mid-type.
                if (/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(v)) setColor(v.toLowerCase());
                else setColor(v);
              }}
              placeholder="#3b82f6"
            />
          </div>
        </div>

        <div className="flex justify-end gap-2">
          <button
            type="button"
            className={cn(
              'rounded px-3 py-1.5 text-[11px] font-medium transition-colors',
              'border border-border cursor-pointer bg-transparent text-muted-foreground hover:bg-accent hover:text-foreground',
            )}
            onClick={onClose}
          >
            {t('dialog.cancel', 'Cancel')}
          </button>
          <button
            type="submit"
            disabled={!systemType.trim()}
            className={cn(
              'rounded px-3 py-1.5 text-[11px] font-medium transition-colors',
              'border-none cursor-pointer bg-[var(--color-accent)] text-white hover:opacity-90',
              'disabled:opacity-50 disabled:cursor-not-allowed',
            )}
          >
            {dialogConfirm}
          </button>
        </div>
      </form>
    </div>
  );
}
